-- This pulls out recent the latest PECOS addresses, by NPI, where the update darte was after 2022
-- YEAR(IDR_TRANS_OBSLT_TS) = 9999 filters out all not-current records. 
SELECT 
    PRVDR_NPI_NUM,
    ADR_TYPE_DESC,
    LINE_1_ADR,
    LINE_2_ADR,
    GEO_USPS_STATE_CD,
    ZIP5_CD,
    ZIP4_CD,
    CNTRY_CD,
    PHNE_NUM,
    PHNE_EXTNSN_NUM,
    FAX_NUM,
    IDR_UPDT_TS,
    YEAR(IDR_UPDT_TS) AS IDR_UPDT_TS_YEAR,
    IDR_TRANS_OBSLT_TS,
    YEAR(IDR_TRANS_OBSLT_TS) AS IDR_TRANS_OBSLT_TS_YEAR,
    IDR_TRANS_EFCTV_TS,
    YEAR(IDR_TRANS_EFCTV_TS) AS IDR_TRANS_EFCTV_TS_YEAR
    
FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_ADR_HSTRY
WHERE YEAR(IDR_TRANS_OBSLT_TS) = 9999 AND YEAR(IDR_TRANS_EFCTV_TS) > 2022 AND ADR_TYPE_DESC = 'PRACTICE'